Repository ansible/ansible-dev-environment, pull requests merged in 2023-11, with the labels that each got.

#60 Rename project to ansible-development-environment
  .config/dictionary.txt
  .gitignore
  .pre-commit-config.yaml
  .vscode/launch.json
  README.md
  pyproject.toml
  src/ansible_development_environment/__init__.py
  src/ansible_development_environment/__main__.py
  src/ansible_development_environment/_version.py
  src/ansible_development_environment/_version.pyi
  src/ansible_development_environment/arg_parser.py
  src/ansible_development_environment/cli.py
  src/ansible_development_environment/collection.py
  src/ansible_development_environment/config.py
  src/ansible_development_environment/output.py
  src/ansible_development_environment/subcommands/__init__.py
  src/ansible_development_environment/subcommands/checker.py
  src/ansible_development_environment/subcommands/inspector.py
  src/ansible_development_environment/subcommands/installer.py
  src/ansible_development_environment/subcommands/lister.py
  src/ansible_development_environment/subcommands/treemaker.py
  src/ansible_development_environment/subcommands/uninstaller.py
  src/ansible_development_environment/tree.py
  src/ansible_development_environment/utils.py
  src/pip4a/__main__.py
  tests/integration/test_basic.py
  tests/unit/test_tree.py
  tests/unit/test_utils.py
Labels: bug

#66 Set Python 3.10 as minimum version
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement

#71 Upgrade Ruff target version to Python 3.10
  pyproject.toml
  src/ansible_development_environment/subcommands/treemaker.py
  src/ansible_development_environment/tree.py
  src/ansible_development_environment/utils.py
Labels: skip-changelog
