Repository ansible/ansible-dev-environment, pull requests merged in 2023-12, with the labels that each got.

#72 Add support for Python 3.12
  .github/workflows/tox.yml
  pyproject.toml
  tests/integration/test_basic.py
Labels: enhancement

#64 Setup mkdocs
  .config/requirements-docs.txt
  .github/workflows/tox.yml
  .readthedocs.yml
  cspell.config.yaml
  docs/index.md
  mkdocs.yml
  pyproject.toml
  tox.ini
Labels: documentation

#63 Homogenize GHA config
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#81 Add macos to test matrix
  .github/workflows/tox.yml
Labels: skip-changelog
