Repository ansible/ansible-dev-environment, pull requests merged in 2024-04, with the labels that each got.

#128 Fix installation of local collection in editable mode
  .pre-commit-config.yaml
  src/ansible_dev_environment/subcommands/installer.py
Labels: bug

#124 Suggest adt install
  .config/constraints.txt
  .config/requirements-docs.in
  .readthedocs.yml
  docs/index.md
  mkdocs.yml
Labels: documentation, skip-changelog

#140 Add system site package flag
  .config/dictionary.txt
  src/ansible_dev_environment/arg_parser.py
  src/ansible_dev_environment/config.py
  tests/unit/test_config.py
Labels: enhancement

#144 Allow collection install if source is not yet a git repository
  .config/dictionary.txt
  .vscode/settings.json
  pyproject.toml
  src/ansible_dev_environment/subcommands/installer.py
  tests/unit/conftest.py
  tests/unit/test_installer.py
Labels: bug
