Repository ansible/ansible-dev-environment, pull requests merged in 2025-04, with the labels that each got.

#311 Better mock of get_terminal_width, UV constraints, disable broken tests on py313
  .config/dictionary.txt
  .config/pydoclint-baseline.txt
  pyproject.toml
  tests/integration/test_basic.py
  tests/unit/test_installer.py
  tests/unit/test_output.py
  tox.ini
Labels: skip-changelog

#309 Update pre-commit hooks
  .config/pydoclint-baseline.txt
  .pre-commit-config.yaml
  src/ansible_dev_environment/subcommands/treemaker.py
Labels: skip-changelog

#314 Replace black with ruff
  .config/constraints.txt
  .config/requirements-test.in
  .pre-commit-config.yaml
  .prettierrc.yaml
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  docs/index.md
  pyproject.toml
Labels: skip-changelog, dependencies

#315 Add environment variable support for select parameters
  src/ansible_dev_environment/arg_parser.py
  src/ansible_dev_environment/cli.py
  src/ansible_dev_environment/config.py
  src/ansible_dev_environment/utils.py
  tests/integration/test_basic.py
  tests/unit/test_cli.py
  tests/unit/test_cli_deprecated.py
  tests/unit/test_cli_precedence.py
  tests/unit/test_config.py
  tests/unit/test_installer.py
  tests/unit/test_treemaker.py
  tests/unit/test_utils.py
Labels: enhancement

#317 Enable cli tab completion
  .config/requirements-test.in
  .pre-commit-config.yaml
  src/ansible_dev_environment/arg_parser.py
  src/ansible_dev_environment/cli.py
  tests/unit/test_cli.py
Labels: enhancement

#319 Allow user specified ansible-core version
  src/ansible_dev_environment/arg_parser.py
  src/ansible_dev_environment/subcommands/installer.py
  tests/integration/test_basic.py
Labels: enhancement

#320 Allow user specified python interpreter
  src/ansible_dev_environment/arg_parser.py
  src/ansible_dev_environment/config.py
  tests/integration/test_user_python.py
  tests/unit/test_config.py
Labels: enhancement

#321 Enable devel testing job
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#322 Fix optional dependency installation
  .config/constraints.txt
  .config/pydoclint-baseline.txt
  .pre-commit-config.yaml
  src/ansible_dev_environment/subcommands/installer.py
  src/ansible_dev_environment/utils.py
  tests/integration/test_basic.py
  tests/unit/test_utils.py
Labels: bug
